/**
 * Default preflop hand ranking.
 *
 * {@link DEFAULT_PREFLOP_RANKING} lists the 169 canonical hand classes
 * (canonical 169 order from `@poker/core`) strongest-first by ALL-IN EQUITY
 * VS ONE UNIFORMLY RANDOM HAND — the standard "raw strength" ordering
 * (AA 85% … 32o 32%).
 *
 * ## Provenance
 *
 * Generated by `tools/gen-ranking.ts` in this package: fixed-seed Monte
 * Carlo (@poker/rng streams, path "ranges/default-preflop-ranking/v1",
 * 50 000 trials per class) using a naive-but-correct best-of-21 five-card
 * evaluator. The per-class equities (inline comments below, in %) agree with
 * published heads-up-vs-random tables to within MC noise (~0.2 pp standard
 * error), so adjacent near-ties (e.g. KQo vs A9s) may sit in either order.
 * That is fine: this ranking exists for SOFT percentile thresholds
 * (topPercentByRanking, tighten, polarize) where a one-slot swap moves a
 * weight by a sliver — it is NOT a solver artifact and carries no positional
 * or playability information. Re-run the tool to regenerate.
 */

import { HAND169_COUNT } from "@poker/core";

// prettier-ignore
const DEFAULT_PREFLOP_RANKING_DATA: readonly number[] = [
  0, 1, 2, 3, 4, 5, 6, 13, // AA 84.9  KK 82.7  QQ 80.1  JJ 77.6  TT 75.2  99 72.3  88 69.6  AKs 67.1
  14, 7, 15, 91, 16, 92, 93, 25, // AQs 66.4  77 66.3  AJs 65.8  AKo 65.0  ATs 64.6  AQo 64.3  AJo 63.4  KQs 63.3
  8, 94, 17, 26, 18, 27, 103, 19, // 66 63.0  ATo 62.6  A9s 62.6  KJs 62.4  A8s 62.0  KTs 61.9  KQo 61.9  A7s 61.4
  95, 104, 28, 36, 21, 9, 96, 20, // A9o 61.1  KJo 60.6  K9s 60.3  QJs 60.2  A5s 60.2  55 60.1  A8o 59.8  A6s 59.8
  105, 37, 97, 22, 29, 23, 114, 106, // KTo 59.8  QTs 59.5  A7o 58.9  A4s 58.9  K8s 58.3  A3s 58.2  QJo 58.1  K9o 58.1
  98, 38, 30, 99, 24, 46, 115, 10, // A6o 57.6  Q9s 57.6  K7s 57.5  A5o 57.4  A2s 57.4  JTs 57.3  QTo 57.2  44 57.1
  100, 31, 107, 39, 47, 101, 32, 116, // A4o 56.8  K6s 56.5  K8o 56.3  Q8s 56.1  J9s 55.9  A3o 55.9  K5s 55.7  Q9o 55.5
  102, 124, 33, 108, 109, 40, 34, 55, // A2o 55.2  JTo 54.9  K4s 54.9  K7o 54.8  K6o 54.4  Q7s 54.3  K3s 54.0  T9s 53.9
  11, 48, 35, 117, 41, 125, 42, 110, // 33 53.8  J8s 53.6  K2s 53.6  Q8o 53.6  Q6s 53.4  J9o 53.2  Q5s 52.8  K5o 52.7
  49, 56, 111, 43, 44, 118, 112, 133, // J7s 52.6  T8s 52.3  K4o 52.2  Q4s 52.0  Q3s 51.8  Q7o 51.6  K3o 51.5  T9o 51.4
  126, 119, 57, 63, 50, 113, 120, 12, // J8o 51.3  Q6o 51.2  T7s 50.7  98s 50.7  J6s 50.7  K2o 50.6  Q5o 50.3  22 50.2
  45, 51, 127, 134, 64, 58, 121, 52, // Q2s 50.1  J5s 49.8  J7o 49.6  T8o 49.5  97s 49.2  T6s 49.1  Q4o 49.0  J4s 48.7
  70, 53, 141, 135, 122, 128, 123, 129, // 87s 48.4  J3s 48.2  98o 48.1  T7o 48.0  Q3o 47.9  J6o 47.8  Q2o 47.4  J5o 47.2
  54, 59, 65, 60, 142, 71, 130, 136, // J2s 47.2  T5s 47.1  96s 47.1  T4s 46.8  97o 46.6  86s 46.4  J4o 46.2  T6o 46.1
  61, 76, 66, 131, 148, 72, 62, 143, // T3s 45.9  76s 45.4  95s 45.3  J3o 45.0  87o 44.9  85s 44.8  T2s 44.5  96o 44.5
  132, 137, 67, 138, 68, 77, 149, 81, // J2o 44.3  T5o 44.1  94s 43.9  T4o 43.6  93s 43.5  75s 43.5  86o 43.2  65s 43.0
  73, 144, 139, 69, 154, 140, 78, 85, // 84s 42.7  95o 42.7  T3o 42.6  92s 42.6  76o 42.3  T2o 41.9  74s 41.9  54s 41.7
  150, 82, 74, 145, 155, 75, 159, 79, // 85o 41.3  64s 41.2  83s 41.0  94o 40.5  75o 40.4  82s 40.2  65o 40.1  73s 40.0
  146, 86, 83, 147, 151, 88, 80, 156, // 93o 40.0  53s 39.6  63s 39.4  92o 39.4  84o 39.2  43s 39.0  72s 38.4  74o 38.3
  163, 160, 87, 152, 84, 153, 89, 157, // 54o 38.2  64o 37.9  52s 37.9  83o 37.5  62s 37.4  82o 37.1  42s 37.1  73o 36.5
  164, 161, 90, 166, 158, 165, 162, 167, // 53o 36.3  63o 36.1  32s 36.0  43o 35.1  72o 34.5  52o 34.4  62o 34.4  42o 33.0
  168, // 32o 32.2
];

/**
 * The 169 hand classes strongest-first by all-in equity vs a random hand.
 * `DEFAULT_PREFLOP_RANKING[0] === 0` (AA); the last entry is 32o.
 */
export const DEFAULT_PREFLOP_RANKING: Uint16Array = Uint16Array.from(DEFAULT_PREFLOP_RANKING_DATA);

if (DEFAULT_PREFLOP_RANKING.length !== HAND169_COUNT) {
  throw new Error("DEFAULT_PREFLOP_RANKING data corrupted: wrong length");
}
